# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bigdecimal'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'ulid'

gem 'rake', require: false
gem 'rbs', require: false
gem "steep", require: false
gem 'rbs-inline', require: false
