namespace :rbs do
  task setup: %i[clean collection rbs_inline]
  task :clean do
    sh 'rm', '-rf', 'sig/generated/'
    sh 'rm', '-rf', '.gem_rbs_collection/'
  end
  task :collection do
    sh 'bundle', 'exec', 'rbs', 'collection', 'install'#, '--frozen'
  end
  task :rbs_inline do
    sh 'bundle', 'exec', 'rbs-inline', '--opt-out', '--output', 'lib/'
  end
end
