namespace :rbs do
  task setup: %i[clean collection rbs_inline]

  task :clean do
    sh 'rm', '-rf', 'sig/generated/'
    sh 'rm', '-rf', '.gem_rbs_collection/'
  end

  task :collection do
    sh 'bundle', 'exec', 'rbs', 'collection', 'install'#, '--frozen'
  end

  task :rbs_inline do
    sh 'bundle', 'exec', 'rbs-inline', '--opt-out', '--output', 'lib/'
  end

  task :watch do
    require 'listen'

    puts '👀 Watching files under lib...'
    listener = Listen.to('lib', relative: true) do |modified, added, deleted|
      unless deleted.empty?
        puts '🚨 Deletion is detected. You may want to reset RBS files by `rake rbs:setup`.'
        deleted.each do |line|
          puts "  #{line}"
        end
      end
      sh 'bundle', 'exec', 'rbs-inline', '--opt-out', '--output', *modified, *added
    end
    listener.start
    begin
      sleep
    rescue Interrupt
      puts '👋 Bye!'
    end
  end
end
